name: Test Private Action

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - review_request_removed
    branches:
      - develop

  workflow_dispatch:

jobs:
  test-private-action:
    name: Test Private Action Job
    uses: plantemoran-appdev-test/.github/.github/workflows/test-private-action-reuse.yml@develop
